import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>Hello!</main>
    </div>
);

export default Home;
