import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Test: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <main>Test!</main>
    <Link href="/">Test</Link>
  </div>
);

export default Test;
